### ISSUE TITLE
new ngAnnotate major version.

### ISSUE THREAD

**Issue by conartist6** [pgilad/broccoli-ng-annotate#2]
The major version of ngAnnotate was released a while ago. It doesn't seem like the plugin code needs to change, there just needs to be a major version bump for the plugin and ngAnnotate in package.json.

**Comment by pgilad** [comment]
Cool, thx for the heads up!

**Comment by pgilad** [comment]
Closed by https://github.com/pgilad/broccoli-ng-annotate/commit/c2f639f3e32cef195bbc43b7b7c1d94df4648a08

**Comment by conartist6** [comment]
Thanks!
